import React from 'react';
import PageBackground from '../components/layout/PageBackground';

const items = [
  {
    title: 'Use of Service',
    text: 'This application is provided for educational and career-guidance purposes. Analysis results are informational and should not be treated as guaranteed hiring outcomes.',
  },
  {
    title: 'User Responsibilities',
    text: 'You are responsible for the accuracy of the GitHub, portfolio, and resume data you submit. Do not upload confidential or restricted documents.',
  },
  {
    title: 'AI-Generated Content',
    text: 'Outputs are generated by AI models and may occasionally contain incorrect or incomplete recommendations. Use your own judgment before acting on results.',
  },
  {
    title: 'Availability',
    text: 'Service availability may vary due to third-party limits (for example API rate limits), maintenance periods, or infrastructure downtime.',
  },
];

export default function Terms() {
  return (
    <div style={{ minHeight: '100%' }}>
      <PageBackground />
      <div style={{ position: 'relative', zIndex: 1, maxWidth: 900, margin: '0 auto', padding: '54px 24px 80px' }}>
        <span className="badge" style={{ background: 'var(--amber-dim)', color: 'var(--amber)', border: '1px solid rgba(245,158,11,0.2)', marginBottom: 14 }}>
          Terms
        </span>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(30px,5vw,44px)', fontWeight: 800, letterSpacing: '-0.03em', color: 'var(--text-primary)', marginBottom: 12 }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.8, marginBottom: 20 }}>
          These are placeholder terms with dummy data for UI structure.
        </p>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {items.map((item) => (
            <div key={item.title} className="card" style={{ padding: '18px 16px' }}>
              <h3 style={{ fontFamily: 'var(--font-display)', fontSize: 16, marginBottom: 8, color: 'var(--text-primary)' }}>{item.title}</h3>
              <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.75 }}>{item.text}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
